Temp fix
hatchways/team-snowman pull request #83
Opened 2021-11-25 02:29 UTC by hodge-jai

### What this PR does (required):
- Fixes issue with protected routes where the components weren't rendering/loading properly on page refresh and manual url entry

2021-11-25 12:44 UTC, ezeilo-su requested changes
Looks good! Please resolve the merge conflicts in this branch.

2021-11-25 12:44 UTC, ezeilo-su commented on client/src/components/EditProfile/EditPhoto/EditPhoto.tsx
> +                <input
Use MUI `TextField` component for this `<input>`

2021-11-25 14:10 UTC, rajivtitus commented on client/src/components/ProtectedRoute/ProtectedRoute.tsx
> +  const [authenticated, setAuth] = useState<boolean>(false);
```suggestion
  const [authenticated, setAuthenticated] = useState<boolean>(false);
```
What is the reason for having a state here? The previous implementation of the protected route using the logged in user object (from AuthContext) accomplished the same in a simpler way :)

2021-11-26 19:23 UTC, rajivtitus commented
Closing this PR as the protected route issue was fixed in another PR

2021-11-26 19:23 UTC, closed without merging