In payment
hatchways/team-snowman pull request #98
Opened 2021-11-26 03:45 UTC by samsoncsyu7777

### What this PR does (required):
- createPaymentIntent service to create payment intent in Stripe to confirm the payment
- create @route POST /:id/checkout-with-created-intent route to get Customer id or create a new Customer from Stripe before confirming the payment
- create confirmPayments API call in FE to pass three parameters to /:id/checkout-with-created-intent: totalCost, default payment method, and user id
- create a confirm payment button with totalCost as the parameter and gather payment method and user id from profile context and user context

### Screenshots / Videos (front-end only):
![Screenshot 2021-11-25 at 9 38 08 PM](https://user-images.githubusercontent.com/30422337/143523571-ffca75c7-5962-407c-becf-2ebc5f4f2d23.png)

### Any information needed to test this feature (required):
The button will be integrated into request page and tested later.

### Any issues with the current functionality (optional):

2021-11-26 12:05 UTC, ezeilo-su requested changes
Remarkable work on this one, though it took a lot all those changes :smiley: 
Please see the review comments and address them. 
Happy coding!

2021-11-26 12:05 UTC, sundayezeilo commented on client/src/components/EditProfile/EditPhoto/EditPhoto.tsx
> +              <input
Please always use MUI components whenever possible. Use a `TextField` component for this one.

2021-11-26 12:05 UTC, sundayezeilo commented on server/controllers/payment.js
> +// @access Private
Good documentation

2021-11-26 12:05 UTC, sundayezeilo commented on server/controllers/payment.js
> +// @access Private
:+1:

2021-11-26 12:05 UTC, sundayezeilo commented on server/controllers/payment.js
> +// @access Private
:+1:

2021-11-26 12:05 UTC, ezeilo-su commented on server/controllers/payment.js
> +// @access Private
:+1:

2021-11-26 12:05 UTC, ezeilo-su commented on server/controllers/payment.js
> +// @access Private
Nice documentation

2021-11-26 13:07 UTC, samsoncsyu7777 commented on client/src/components/EditProfile/EditPhoto/EditPhoto.tsx
> +              <input
There are some features needed that are not supported by TextField.

2021-11-26 13:07 UTC, samsoncsyu7777 commented on server/controllers/payment.js
> +// @access Private
Thanks.

2021-11-26 13:07 UTC, samsoncsyu7777 commented on server/controllers/payment.js
> +// @access Private
Thanks.

2021-11-26 13:07 UTC, samsoncsyu7777 commented on server/controllers/payment.js
> +// @access Private
Thanks.

2021-11-26 13:07 UTC, samsoncsyu7777 commented on server/controllers/payment.js
> +// @access Private
Thanks.

2021-11-26 13:12 UTC, ezeilo-su commented on client/src/components/EditProfile/EditPhoto/EditPhoto.tsx
> +              <input
> There are some features needed that are not supported by TextField.

That's true for file upload. :+1:

2021-11-26 13:18 UTC, samsoncsyu7777 commented on server/controllers/payment.js
> +// @access Private
Thanks.

2021-11-30 20:17 UTC, rajivtitus approved these changes
Impressive work with the entire payment feature 💯

2021-11-30 22:45 UTC, merged